model: 'art'
network: 'ro_34'
task: 'snake'
resume: true
gpus: (1,)

train:
    optim: 'adam'
    lr: 1e-4
    milestones: (80, 120, 160, 180, 260)
    gamma: 0.5
    batch_size: 6
    dataset: 'ArtTrain'
    num_workers: 4
    epoch: 300
test:
    dataset: 'ArtMini'
    batch_size: 1

heads: {'ct_hm': 1, 'wh': 2}
segm_or_bbox: 'segm'
